enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[YouTube]
enabled = false
build-mode = "both"
patches-source = "https://github.com/inotia00/revanced-patches"
integrations-source = "https://github.com/inotia00/revanced-integrations"
cli-source = "https://github.com/inotia00/revanced-cli"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Music]
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"

[Twitter]
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[TikTok]
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Reddit]
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Spotify]
build-mode = "both"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"