enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "YT-Advanced/ReX-patches/tree/spoof"
integrations-source = "YT-Advanced/ReX-integrations/"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'MaterialYou' 'Visual preferences icons'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Disable haptic feedback'"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "YT-Advanced/ReX-patches/tree/spoof"
integrations-source = "YT-Advanced/ReX-integrations/"
arch = "arm64-v8a"
build-mode = "both"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"
build-mode = "both"

