enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

[YouTube] #works
build-mode = "both"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" # fallback

[YouTube-Extended] #works
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Music] #works
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"

[Music-Extended] #works
app-name = "Music"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"

[TikTok] #works
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Reddit-Extended] #maybe?
build-mode = "both"
rv-brand = "ReVanced Extended"
uptodown-dlurl = "https://reddit-official-app.fr.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Spotify] #works
build-mode = "both"
uptodown-dlurl = "https://spotify.fr.uptodown.com/android"
arch = "arm64-v8a"

[Twitch] #works
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
uptodown-dlurl = "https://twitch-app.fr.uptodown.com/android"

[MemeGenerator] #works
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/zombodroid/meme-generator-free/"
uptodown-dlurl = "https://meme-generator-free.fr.uptodown.com/android"

[Strava] #works
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-running-and-cycling-gps/"
uptodown-dlurl = "https://strava.fr.uptodown.com/android"

[Yuka] #works
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/yuka-apps/yuka-food-cosmetic-scan/"
uptodown-dlurl = "https://yuka.fr.uptodown.com/android"

[Photomath]
build-mode = "both"
version = "auto"
arch = "all"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath/"

[Transit] #works
patches-source = "andronedev/revanced-patches"
version = "auto"
arch = "arm64-v8a"
rv-brand = "andronedev"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/transit-app-inc/"

[Geniusscan]
build-mode = "both"
enabled = "false"
patches-source = "andronedev/revanced-patches"
rv-brand = "andronedev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/the-grizzly-labs/genius-scan-pdf-scanner-2/"
arch = "both"

