enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

[YouTube] #works
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" # fallback

[Music] #works
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "arm64-v8a"

[Music-Extended] #works
app-name = "Music"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "arm64-v8a"

[YouTube-Extended] #works
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Twitter] #works
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
build-mode = "both"
rv-brand = "Piko"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
included-patches = "'Bring back twitter'"
excluded-patches = "'Dynamic color'"

[Twitter-material-design] #works
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
build-mode = "both"
rv-brand = "Piko"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
included-patches = "'Bring back twitter'"

[X] #works
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
build-mode = "both"
rv-brand = "Piko"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
excluded-patches = "'Dynamic color'"

[X-material-design] #works
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
build-mode = "both"
rv-brand = "Piko"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"

[TikTok] #works
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Reddit-Extended] #maybe?
build-mode = "both"
version = "latest"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReVanced Extended"
uptodown-dlurl = "https://reddit-official-app.fr.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Spotify] #works
build-mode = "both"
version = "latest"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Twitch] #works
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
uptodown-dlurl = "https://twitch-app.fr.uptodown.com/android"

[Windyapp] #maybe?
build-mode = "both"
version = "auto"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[MemeGenerator] #works
build-mode = "both"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/zombodroid/meme-generator-free/"
uptodown-dlurl = "https://meme-generator-free.fr.uptodown.com/android"

[Strava] #works
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-running-and-cycling-gps/"
uptodown-dlurl = "https://strava.fr.uptodown.com/android"

[Yuka] #works
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/yuka-apps/yuka-food-cosmetic-scan/"
uptodown-dlurl = "https://yuka.fr.uptodown.com/android"

[Photomath]
build-mode = "both"
version = "auto"
arch = "all"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath/"

[Transit] #works
patches-source = "andronedev/revanced-patches"
build-mode = "both"
version = "auto"
rv-brand = "andronedev"
uptodown-dlurl = "https://transit.fr.uptodown.com/android"

[Geniusscan]
enabled = "false"
patches-source = "andronedev/revanced-patches"
build-mode = "both"
rv-brand = "andronedev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/the-grizzly-labs/genius-scan-pdf-scanner-2/"
arch = "both"
